### ISSUE TITLE
Build for 3.7

### ISSUE THREAD

**Issue by yoyo-sincerely** [sfbahr/PyCrypto-Wheels#8]

**Comment by yoyo-sincerely** [comment]
hi, sfbahr. I'm a student. I'm using python 3.7,could you upgrade to python 3.7?thanks

**Comment by sfbahr** [comment]
It's not worth it since PyCrypto isn't supported anymore. Try the cryptography or PyCryptodome packages

https://github.com/dlitz/pycrypto/issues/238
